name: Testes end to end cypress
on: push
jobs:
        
        chrome:
            runs-on: ubuntu-22.04
            name: E2E on Chrome
            steps:
              - uses: actions/checkout@v4
              - uses: cypress-io/github-action@v6
                with:
                  browser: chrome

        firefox:
                    runs-on: windows-2022
                    name: E2E on Firefox
                    steps:
                      - uses: actions/checkout@v4
                      - uses: cypress-io/github-action@v6
                        with:
                          browser: firefox
        edge:
                            runs-on: ubuntu-22.04
                            name: E2E on Edge
                            steps:
                              - uses: actions/checkout@v4
                              - uses: cypress-io/github-action@v6
                                with:
                                  browser: edge
                              
                              - uses: actions/upload-artifact@v3
                                with:
                                    name: Meu relatório goianinho
                                    path: cypress/reports/html # or path/to/artifact